FROM node:18

WORKDIR /frontend

# Copier les fichiers de dépendances et installer
COPY package.json package-lock.json ./
RUN npm install

# Copier le reste du projet
COPY . .

# Variable pour l'URL de l'API
ENV VITE_API_URL=http://localhost:8000

# Exposer le port utilisé par Vite en mode développement
EXPOSE 5173

# Commande pour démarrer le serveur de développement
CMD ["npm", "run", "dev", "--", "--host"]
