FROM node:18

WORKDIR /frontend

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Variable pour l'URL de l'API
ENV VITE_API_URL=http://localhost:8000

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
