
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
      interval: 10s
      retries: 5

  fastapi_backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["fastapi", "dev", "backend/main.py"]

volumes:
  pg_data:
