
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
      interval: 10s
      retries: 5

  fastapi_backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "python -m backend.app.db.card_ajout && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"]


    dns:
      - 8.8.8.8  # Serveur DNS public de Google

  frontend:
    image: node:20  # Remplace "node:18" par "node:20"
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://fastapi_backend:8000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    depends_on:
      - fastapi_backend
    dns:
      - 8.8.8.8




volumes:
  pg_data:
