FROM python:3.10

# Définir le répertoire de travail
WORKDIR /backend

# Copier les fichiers du backend
COPY . .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Définition des ports via une variable d'environnement
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000

EXPOSE $UVICORN_PORT

CMD ["uvicorn", "app.main:app", "--host", "$UVICORN_HOST", "--port", "$UVICORN_PORT"]
